<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/assets/logos/SN_web_lightmode.png" width="300" alt="cognitiveclass.ai logo"  />
</center>

# Simple APIs

## Random User and Fruitvice API Examples

Estimated time needed: **25** minutes

## Objectives

After completing this lab you will be able to:

*   Load and use RandomUser API, using `RandomUser()` Python library
*   Load and use Fruitvice API, using `requests` Python library

The purpose of this notebook is to provide more examples on how to use simple APIs. As you have already learned from previous videos and notebooks, API stands for Application Programming Interface and is a software intermediary that allows two applications to talk to each other.

The advantages of using APIs:

*   **Automation**. Less human effort is required and workflows can be easily updated to become faster and more\
    productive.
*   **Efficiency**. It allows to use the capabilities of one of the already developed APIs than to try to
    independently implement some functionality from scratch.

The disadvantage of using APIs:

*   **Secirity**. If the API is poorly integrated, it means it will be vulnerable to attacks, resulting in data\
    breeches or losses having financial or reputation implications.

One of the applications we will use in this notebook is Random User Generator. RandomUser is an open-source, free API providing developers with randomly generated users to be used as placeholders for testing purposes. This makes the tool similar to Lorem Ipsum, but is a placeholder for people instead of text. The API can return multiple results, as well as specify generated user details such as gender, email, image, username, address, title, first and last name, and more. More information on [RandomUser](https://randomuser.me/documentation?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkPY0101ENSkillsNetwork19487395-2022-01-01#intro) can be found here.

Another example of simple API we will use in this notebook is Fruitvice application. The Fruitvice API webservice which provides data for all kinds of fruit! You can use Fruityvice to find out interesting information about fruit and educate yourself. The webservice is completely free to use and contribute to.

## Example 1: RandomUser API

Bellow are Get Methods parameters that we can generate. For more information on the parameters, please visit this [documentation](https://randomuser.me/documentation?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkPY0101ENSkillsNetwork19487395-2022-01-01) page.

## **Get Methods**

*   get_cell()
*   get_city()
*   get_dob()
*   get_email()
*   get_first_name()
*   get_full_name()
*   get_gender()
*   get_id()
*   get_id_number()
*   get_id_type()
*   get_info()
*   get_last_name()
*   get_login_md5()
*   get_login_salt()
*   get_login_sha1()
*   get_login_sha256()
*   get_nat()
*   get_password()
*   get_phone()
*   get_picture()
*   get_postcode()
*   get_registered()
*   get_state()
*   get_street()
*   get_username()
*   get_zipcode()

To start using the API you can install the `randomuser` library running the `pip install` command.

In [28]:
!pip install randomuser

Collecting randomuser
  Downloading randomuser-1.6.tar.gz (5.0 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: randomuser
  Building wheel for randomuser (setup.py) ... done
  Created wheel for randomuser: filename=randomuser-1.6-py3-none-any.whl size=5067 sha256=58a029321057e38c1798ccb2e884676a7a4506df605242c596f4f961c2ccdf12
  Stored in directory: /home/jupyterlab/.cache/pip/wheels/21/10/7b/c13bc3e24a3c1000a34554802ad8aa0ff27df56366998a0473
Successfully built randomuser
Installing collected packages: randomuser
Successfully installed randomuser-1.6

Then, we will load the necessary libraries.

In [29]:
from randomuser import RandomUser
import pandas as pd

First, we will create a random user object, r.

In [3]:
r = RandomUser()

Then, using `generate_users()` function, we get a list of random 10 users.

In [4]:
some_list = r.generate_users(10)

In [5]:
some_list

[<randomuser.RandomUser at 0x7fb1ba89fdd0>,
 <randomuser.RandomUser at 0x7fb1ba89fe10>,
 <randomuser.RandomUser at 0x7fb1ba89fe50>,
 <randomuser.RandomUser at 0x7fb1ba89fe90>,
 <randomuser.RandomUser at 0x7fb1ba89fed0>,
 <randomuser.RandomUser at 0x7fb1ba89ff50>,
 <randomuser.RandomUser at 0x7fb1ba89ff90>,
 <randomuser.RandomUser at 0x7fb1ba89ffd0>,
 <randomuser.RandomUser at 0x7fb1ba8a3050>,
 <randomuser.RandomUser at 0x7fb1ba89ff10>]

The **"Get Methods"** functions mentioned at the beginning of this notebook, can generate the required parameters to construct a dataset. For example, to get full name, we call `get_full_name()` function.

In [6]:
name = r.get_full_name()

Let's say we only need 10 users with full names and their email addresses. We can write a "for-loop" to print these 10 users.

In [7]:
for user in some_list:
    print (user.get_full_name()," ",user.get_email())

Lola Hunter   lola.hunter@example.com
Jeffrey Montgomery   jeffrey.montgomery@example.com
Chad Nelson   chad.nelson@example.com
Joey Simpson   joey.simpson@example.com
سورنا سلطانی نژاد   swrn.sltnynjd@example.com
Julius Couri   julius.couri@example.com
Caroline Petersen   caroline.petersen@example.com
Kirk Dunn   kirk.dunn@example.com
Dajana Moog   dajana.moog@example.com
Okan Okumuş   okan.okumus@example.com

## Exercise 1

In this Exercise, generate photos of the random 5 users.

In [11]:
## Write your code here
some_list2 = r.generate_users(5)
some_list2
for user in some_list2:
    print(user.get_picture())

https://randomuser.me/api/portraits/women/32.jpg
https://randomuser.me/api/portraits/men/15.jpg
https://randomuser.me/api/portraits/men/10.jpg
https://randomuser.me/api/portraits/men/85.jpg
https://randomuser.me/api/portraits/men/31.jpg

<details><summary>Click here for the solution</summary>

```python
for user in some_list:
    print (user.get_picture())
```

</details>

To generate a table with information about the users, we can write a function containing all desirable parameters. For example, name, gender, city, etc. The parameters will depend on the requirements of the test to be performed. We call the Get Methods, listed at the beginning of this notebook. Then, we return pandas dataframe with the users.

In [12]:
def get_users():
    users =[]
     
    for user in RandomUser.generate_users(10):
        users.append({"Name":user.get_full_name(),"Gender":user.get_gender(),"City":user.get_city(),"State":user.get_state(),"Email":user.get_email(), "DOB":user.get_dob(),"Picture":user.get_picture()})
      
    return pd.DataFrame(users)

In [13]:
get_users()

,Name,Gender,City,State,Email,DOB,Picture
0,Kaitlin Ramirez,female,Salford,County Down,kaitlin.ramirez@example.com,1988-01-30T01:34:38.983Z,https://randomuser.me/api/portraits/women/8.jpg
1,Jente Knubben,male,Wenum Wiesel,Groningen,jente.knubben@example.com,1995-03-28T18:36:37.893Z,https://randomuser.me/api/portraits/men/65.jpg
2,Paul Till,male,Zell am Harmersbach,Bremen,paul.till@example.com,1961-10-11T00:06:54.636Z,https://randomuser.me/api/portraits/men/15.jpg
3,Charlotte Harper,female,Wells,Cornwall,charlotte.harper@example.com,1994-07-23T19:27:20.041Z,https://randomuser.me/api/portraits/women/0.jpg
4,Jonathan Nichols,male,Plymouth,Essex,jonathan.nichols@example.com,1954-12-06T06:02:04.585Z,https://randomuser.me/api/portraits/men/36.jpg
5,Norberto Nunes,male,Jaú,Espírito Santo,norberto.nunes@example.com,1983-10-08T08:57:29.098Z,https://randomuser.me/api/portraits/men/36.jpg
6,Valerie Guillot,female,Zuchwil,Appenzell Innerrhoden,valerie.guillot@example.com,1958-09-11T15:41:05.784Z,https://randomuser.me/api/portraits/women/2.jpg
7,Valdinélia Novaes,female,Rio Grande,Pernambuco,valdinelia.novaes@example.com,1986-10-25T09:33:12.881Z,https://randomuser.me/api/portraits/women/11.jpg
8,Bella Wood,female,Lower Hutt,Nelson,bella.wood@example.com,1948-08-22T18:09:46.866Z,https://randomuser.me/api/portraits/women/9.jpg
9,Alma Økland,female,Ytre Enebakk,Finnmark - Finnmárku,alma.okland@example.com,1966-06-14T10:39:37.425Z,https://randomuser.me/api/portraits/women/10.jpg

In [15]:
df1 = pd.DataFrame(get_users())

Now we have a *pandas* dataframe that can be used for any testing purposes that the tester might have.

## Example 2: Fruitvice API

Another, more common way to use APIs, is through `requests` library. The next lab, Requests and HTTP, will contain more information about requests.

We will start by importing all required libraries.

In [2]:
import requests
import json

We will obtain the [fruitvice](https://www.fruityvice.com/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkPY0101ENSkillsNetwork19487395-2022-01-01) API data using `requests.get("url")` function. The data is in a json format.

In [17]:
data = requests.get("https://www.fruityvice.com/api/fruit/all")

We will retrieve results using `json.loads()` function.

In [18]:
results = json.loads(data.text)

We will convert our json data into *pandas* data frame.

In [19]:
pd.DataFrame(results)

,genus,name,id,family,order,nutritions
0,Malus,Apple,6,Rosaceae,Rosales,"{'carbohydrates': 11.4, 'protein': 0.3, 'fat':..."
1,Prunus,Apricot,35,Rosaceae,Rosales,"{'carbohydrates': 3.9, 'protein': 0.5, 'fat': ..."
2,Musa,Banana,1,Musaceae,Zingiberales,"{'carbohydrates': 22, 'protein': 1, 'fat': 0.2..."
3,Rubus,Blackberry,64,Rosaceae,Rosales,"{'carbohydrates': 9, 'protein': 1.3, 'fat': 0...."
4,Fragaria,Blueberry,33,Rosaceae,Rosales,"{'carbohydrates': 5.5, 'protein': 0, 'fat': 0...."
5,Prunus,Cherry,9,Rosaceae,None,"{'carbohydrates': 12, 'protein': 1, 'fat': 0.3..."
6,Durio,Durian,60,Malvaceae,Malvales,"{'carbohydrates': 27.1, 'protein': 1.5, 'fat':..."
7,Ficus,Fig,68,Moraceae,Rosales,"{'carbohydrates': 19, 'protein': 0.8, 'fat': 0..."
8,Ribes,Gooseberry,69,Grossulariaceae,Saxifragales,"{'carbohydrates': 10, 'protein': 0.9, 'fat': 0..."
9,Vitis,Grapes,47,Vitaceae,Vitales,"{'carbohydrates': 18.1, 'protein': 0.72, 'fat'..."
10,Malus,GreenApple,72,Rosaceae,Rosales,"{'carbohydrates': 3.1, 'protein': 0.4, 'fat': ..."
11,Psidium,Guava,37,Myrtaceae,Myrtales,"{'carbohydrates': 14, 'protein': 2.6, 'fat': 1..."
12,Apteryx,Kiwi,66,Actinidiaceae,Struthioniformes,"{'carbohydrates': 15, 'protein': 1.1, 'fat': 0..."
13,Citrus,Lemon,26,Rutaceae,Sapindales,"{'carbohydrates': 9, 'protein': 1.1, 'fat': 0...."
14,Citrus,Lime,44,Rutaceae,Sapindales,"{'carbohydrates': 8.4, 'protein': 0.3, 'fat': ..."
15,Vaccinium,Lingonberry,65,Ericaceae,Ericales,"{'carbohydrates': 11.3, 'protein': 0.75, 'fat'..."
16,Litchi,Lychee,67,Sapindaceae,Sapindales,"{'carbohydrates': 17, 'protein': 0.8, 'fat': 0..."
17,Mangifera,Mango,27,Anacardiaceae,Sapindales,"{'carbohydrates': 15, 'protein': 0.82, 'fat': ..."
18,Cucumis,Melon,41,Cucurbitaceae,Cucurbitaceae,"{'carbohydrates': 8, 'protein': 0, 'fat': 0, '..."
19,Citrus,Orange,2,Rutaceae,Sapindales,"{'carbohydrates': 8.3, 'protein': 1, 'fat': 0...."
20,Carica,Papaya,42,Caricaceae,Caricacea,"{'carbohydrates': 11, 'protein': 0, 'fat': 0.4..."
21,Passiflora,Passionfruit,70,Passifloraceae,Malpighiales,"{'carbohydrates': 22.4, 'protein': 2.2, 'fat':..."
22,Pyrus,Pear,4,Rosaceae,Rosales,"{'carbohydrates': 15, 'protein': 0.4, 'fat': 0..."
23,Diospyros,Persimmon,52,Ebenaceae,Rosales,"{'carbohydrates': 18, 'protein': 0, 'fat': 0, ..."
24,Ananas,Pineapple,10,Bromeliaceae,Poales,"{'carbohydrates': 13.12, 'protein': 0.54, 'fat..."
25,Prunus,Plum,71,Rosaceae,Rosales,"{'carbohydrates': 11.4, 'protein': 0.7, 'fat':..."
26,Rubus,Raspberry,23,Rosaceae,Rosales,"{'carbohydrates': 12, 'protein': 1.2, 'fat': 0..."
27,Fragaria,Strawberry,3,Rosaceae,Rosales,"{'carbohydrates': 5.5, 'protein': 0.8, 'fat': ..."
28,Solanum,Tomato,5,Solanaceae,Solanales,"{'carbohydrates': 3.9, 'protein': 0.9, 'fat': ..."
29,Spondias,Umbu,73,Anacardiaceae,0,"{'carbohydrates': 0, 'protein': 0, 'fat': 0, '..."
30,Citrullus,Watermelon,25,Cucurbitaceae,Cucurbitales,"{'carbohydrates': 8, 'protein': 0.6, 'fat': 0...."

The result is in a nested json format. The 'nutrition' column contains multiple subcolumns, so the data needs to be 'flattened' or normalized.

In [20]:
df2 = pd.json_normalize(results)

In [21]:
df2

,genus,name,id,family,order,nutritions.carbohydrates,nutritions.protein,nutritions.fat,nutritions.calories,nutritions.sugar
0,Malus,Apple,6,Rosaceae,Rosales,11.40,0.30,0.40,52,10.30
1,Prunus,Apricot,35,Rosaceae,Rosales,3.90,0.50,0.10,15,3.20
2,Musa,Banana,1,Musaceae,Zingiberales,22.00,1.00,0.20,96,17.20
3,Rubus,Blackberry,64,Rosaceae,Rosales,9.00,1.30,0.40,40,4.50
4,Fragaria,Blueberry,33,Rosaceae,Rosales,5.50,0.00,0.40,29,5.40
5,Prunus,Cherry,9,Rosaceae,None,12.00,1.00,0.30,50,8.00
6,Durio,Durian,60,Malvaceae,Malvales,27.10,1.50,5.30,147,6.75
7,Ficus,Fig,68,Moraceae,Rosales,19.00,0.80,0.30,74,16.00
8,Ribes,Gooseberry,69,Grossulariaceae,Saxifragales,10.00,0.90,0.60,44,0.00
9,Vitis,Grapes,47,Vitaceae,Vitales,18.10,0.72,0.16,69,15.48
10,Malus,GreenApple,72,Rosaceae,Rosales,3.10,0.40,0.10,21,6.40
11,Psidium,Guava,37,Myrtaceae,Myrtales,14.00,2.60,1.00,68,9.00
12,Apteryx,Kiwi,66,Actinidiaceae,Struthioniformes,15.00,1.10,0.50,61,9.00
13,Citrus,Lemon,26,Rutaceae,Sapindales,9.00,1.10,0.30,29,2.50
14,Citrus,Lime,44,Rutaceae,Sapindales,8.40,0.30,0.10,25,1.70
15,Vaccinium,Lingonberry,65,Ericaceae,Ericales,11.30,0.75,0.34,50,5.74
16,Litchi,Lychee,67,Sapindaceae,Sapindales,17.00,0.80,0.44,66,15.00
17,Mangifera,Mango,27,Anacardiaceae,Sapindales,15.00,0.82,0.38,60,13.70
18,Cucumis,Melon,41,Cucurbitaceae,Cucurbitaceae,8.00,0.00,0.00,34,8.00
19,Citrus,Orange,2,Rutaceae,Sapindales,8.30,1.00,0.20,43,8.20
20,Carica,Papaya,42,Caricaceae,Caricacea,11.00,0.00,0.40,43,1.00
21,Passiflora,Passionfruit,70,Passifloraceae,Malpighiales,22.40,2.20,0.70,97,11.20
22,Pyrus,Pear,4,Rosaceae,Rosales,15.00,0.40,0.10,57,10.00
23,Diospyros,Persimmon,52,Ebenaceae,Rosales,18.00,0.00,0.00,81,18.00
24,Ananas,Pineapple,10,Bromeliaceae,Poales,13.12,0.54,0.12,50,9.85
25,Prunus,Plum,71,Rosaceae,Rosales,11.40,0.70,0.28,46,9.92
26,Rubus,Raspberry,23,Rosaceae,Rosales,12.00,1.20,0.70,53,4.40
27,Fragaria,Strawberry,3,Rosaceae,Rosales,5.50,0.80,0.40,29,5.40
28,Solanum,Tomato,5,Solanaceae,Solanales,3.90,0.90,0.20,74,2.60
29,Spondias,Umbu,73,Anacardiaceae,0,0.00,0.00,0.00,0,0.00
30,Citrullus,Watermelon,25,Cucurbitaceae,Cucurbitales,8.00,0.60,0.20,30,6.00

Let's see if we can extract some information from this dataframe. Perhaps, we need to know the family and genus of a cherry.

In [22]:
cherry = df2.loc[df2["name"] == 'Cherry']
(cherry.iloc[0]['family']) , (cherry.iloc[0]['genus'])

('Rosaceae', 'Prunus')

## Exercise 2

In this Exercise, find out how many calories are contained in a banana.

In [24]:
# Write your code here
banana = df2.loc[df2["name"] == "Banana"]
banana.iloc[0]['nutritions.calories']

96

<details><summary>Click here for the solution</summary>

```python
cal_banana = df2.loc[df2["name"] == 'Banana']
cal_banana.iloc[0]['nutritions.calories']
```

</details>

## Exercise 3

This [page](https://github.com/public-apis/public-apis#animals) contains a list of free public APIs. Choose any API of your interest and use it to load/extract some information, as shown in the example above.

1.  Using `requests.get("url")` function, load your data.

In [7]:
# Write your code here
url = 'http://shibe.online/api/shibes'
payload2 = {"count":2, "urls": True, "httpsUrls": False}
r3 = requests.get(url,params=payload2)
r3.headers

{'Date': 'Sun, 11 Sep 2022 14:08:15 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': 'GET, POST, OPTIONS', 'Access-Control-Allow-Headers': 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range', 'Access-Control-Max-Age': '1728000', 'CF-Cache-Status': 'DYNAMIC', 'Report-To': '{"endpoints":[{"url":"https:\\/\\/a.nel.cloudflare.com\\/report\\/v3?s=Zwq3Kf5Y7tAKkbDhJUmKPni2v3SDkxxNJyquNuJbcT729hCdvi4%2BFgUwWZYu1IbhOM5H%2FBMqxFuv7%2FaLM%2FM9b6gIr6CJu2lxCLLGYjNzqAZAgcbj6MDGG37GTjiJwIc%3D"}],"group":"cf-nel","max_age":604800}', 'NEL': '{"success_fraction":0,"report_to":"cf-nel","max_age":604800}', 'Server': 'cloudflare', 'CF-RAY': '7490f96d5a56828d-IAD', 'Content-Encoding': 'gzip', 'alt-svc': 'h3=":443"; ma=86400, h3-29=":443"; ma=86400'}

<details><summary>Click here for the solution</summary>

```python
data2 = requests.get("https://www.fishwatch.gov/api/species")
```

</details>

2.  Retrieve results using `json.loads()` function.

In [43]:
# Write your code here
print(r3.headers['Report-To'])
results3 = pd.json_normalize(json.loads(r3.headers['Report-To'])).loc[0, "endpoints"][0]["url"]
results3

{"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=Zwq3Kf5Y7tAKkbDhJUmKPni2v3SDkxxNJyquNuJbcT729hCdvi4%2BFgUwWZYu1IbhOM5H%2FBMqxFuv7%2FaLM%2FM9b6gIr6CJu2lxCLLGYjNzqAZAgcbj6MDGG37GTjiJwIc%3D"}],"group":"cf-nel","max_age":604800}

'https://a.nel.cloudflare.com/report/v3?s=Zwq3Kf5Y7tAKkbDhJUmKPni2v3SDkxxNJyquNuJbcT729hCdvi4%2BFgUwWZYu1IbhOM5H%2FBMqxFuv7%2FaLM%2FM9b6gIr6CJu2lxCLLGYjNzqAZAgcbj6MDGG37GTjiJwIc%3D'

<details><summary>Click here for the solution</summary>

```python
results2 = json.loads(data2.text)
```

</details>

3.  Convert json data into *pandas* data frame.

In [30]:
# Write your code here
pd.DataFrame(results3)

                                           endpoints   group  max_age
0  {'url': 'https://a.nel.cloudflare.com/report/v...  cf-nel   604800

<details><summary>Click here for the solution</summary>

```python
df3 = pd.DataFrame(results2)
df3
```

</details>

# Congratulations! - You have completed the lab

## Author

[Svitlana Kramar](https://www.linkedin.com/in/svitlana-kramar?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkPY0101ENSkillsNetwork19487395-2022-01-01)

Svitlana is a master’s degree Data Science and Analytics student at University of Calgary, who enjoys travelling, learning new languages and cultures and loves spreading her passion for Data Science.

Copyright © 2020 IBM Corporation. All rights reserved.